---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ui
  description: Testing Farm UI / Oculus
  annotations:
    gitlab.com/project-slug: 'testing-farm/oculus'
    servicenow.com/appcode: TFT-001
    jira/project-key: TFT
    jira/label: Oculus
    feedback/type: JIRA
    feedback/host: https://issues.redhat.com
    feedback/email-to: tft@redhat.com
  tags:
    - ecosystem:rhel
    - ecosystem:public
    - category:testing
    - category:cloud
    - language:javascript
    - language:html5
  links:
    - title: "#testing-farm"
      url: https://redhat.enterprise.slack.com/archives/C03BRN71JAF
      icon: chat
spec:
  type: website
  lifecycle: production
  owner: group:redhat/tft
  domain: quality-community/quality-community
  system: quality-community/testing-farm
